app_name        = app测试
# 错误级别: DEBUG,INFO,WARNING,ERROR,FATAL
log_level       = DEBUG
app_mode        = production
# 管理后台,特殊的权限排除地址
excludeAuthPath = /,/welcome,/loginOut

[mysql]
ip       = 127.0.0.1
port     = 3306
user     = root
password = 123456
database = ginshop

# 是否开启oss, 1 开启, 0 关闭, oss的配置需要在后台管理系统中配置
[oss]
status = 1

# cos 文件存储密钥相关
[cos]
rawURL   = http://xxx-xxx-1312546108.cos.ap-chengdu.myqcloud.com
secretID = AKIDDEyRexxxo79uObXxxxX6O
scretKey = 2xxxS7VxxxsJTN0NSxxxTN3
bucket   = xxx-xxx-1312546108
region   = ap-chengdu

[redis]
ip          = localhost
port        = 6379
database    = 1
redisEnable = true

# 腾讯云sms短信发送
[sms_tencent]
secretId          = AKxxxoallX4PYxxxdR0Lxxx
secretKey         = OxxxSFo8xxx4kCQxxx3Rb
# 指定接入地域域名(默认就近接入)
endpoint          = sms.tencentcloudapi.com
# 指定签名算法(默认为HmacSHA256)
signMethod        = TC3-HMAC-SHA256
# 地域信息:https://cloud.tencent.com/document/api/382/52071#.E5.9C.B0.E5.9F.9F.E5.88.97.E8.A1.A8
region            = ap-guangzhou
# 短信应用ID: 短信SdkAppId在 [短信控制台] 添加应用后生成的实际SdkAppId，示例如1400006666
smsSdkAppId       = 1400xxx
# 短信签名内容: 使用 UTF-8 编码，必须填写已审核通过的签名
signName          = xxx科技
# 模板 ID: 必须填写已审核通过的模板 ID: 普通短信，验证码通用
templateId_common = 151xxx
# 短信session_key, 后面还要加对应短信类型和电话号码,eg = sms.captcha115555555555
session_key       = sms:captcha
# 验证码时间
# 有效时间, 单位:秒
captcha_expiring  = 120
# 间隔时间, 单位:秒
captcha_interval  = 60
